mohitahlawat2001/Loco-Musica

- src/components/Cart.js
- src/components/RestaurantMenu.js
Please check the images, I have done changes, Thanks bro
> Duplicate Food Item Added to Cart #6

- package-lock.json
- package.json
- src/components/Body.js
Hey @mohitahlawat2001! I have **updated the search filter** and enhanced its **UI appearance.** closes #10  
https://github.com/user-attachments/assets/10e16755-d4d8-40f5-9dbb-04a761886761
> Search Bar Updated

- package-lock.json
- package.json
- src/components/Footer.js
https://github.com/user-attachments/assets/08f623db-80b4-4e4c-96b1-53abdb34c329
I’ve made updates to the footer design as outlined in Issue #13. The new design is cleaner, with improved layout and responsiveness. I also added hover effects for the social media icons, included a feedback form, and made sure everything works smoothly across devices.
I've attached a video showcasing the changes. Let me know if you’d like any adjustments!
> Improved Footer design #13

- package-lock.json
- package.json
- src/components/Footer.js
Reverts mohitahlawat2001/Loco-Musica#17
> Revert "Improved Footer design #13"

- package-lock.json
- package.json
- src/components/Body.js
Reverts mohitahlawat2001/Loco-Musica#14
> Revert "Search Bar Updated"

- package-lock.json
- package.json
- src/components/Body.js
Reverts mohitahlawat2001/Loco-Musica#20
> Revert "Revert "Search Bar Updated""

- package-lock.json
- package.json
- src/components/Body.js
Reverts mohitahlawat2001/Loco-Musica#21
> Revert "Revert "Revert "Search Bar Updated"""

- index.css
Fixed #29 
Added customised styles to the scrollbar according to the theme.
- Whitish Track
- Light Pinkish Thumb
- Dark Pinkish Thumb : Hover
I had used the theme from the home page.
I am open to any changes needed for this part.
> Styled scrollbar

- src/components/Cart.js
- src/components/RestaurantMenu.js
- src/utils/cartSlice.js
Fixes: #24 
- User can change the number if items from menu page itself
- Quantity of Cart items are stored in redux
- Changed addToCart and removeFromCart function in cartSlice
- Made another function "removeItemFromCart" to bring that quantity to 0
Checkout the changes below to see the added functionality
https://github.com/user-attachments/assets/35a349b5-b72d-45b1-81e9-e38be5b5767e
> User can regulate the quanitity of food items from menu page itself

- package-lock.json
- package.json
- src/components/Firebase.js
- src/components/GoogleLogin.js
- src/components/Login.js
**Description:** 
- Added Google Sign-In functionality using Firebase Authentication.
-  Users can log in via their Google account, and their details are stored in Firebase.
- Attached are screenshots showing the Google sign-in popup.
- Used the react-google-button library for the Google Sign-In button.
**React Dependency:**
`npm install react-google-button`
**Firebase Setup Instructions:**
To test this feature, follow these steps:
- Go to your Firebase Console and create a new project (if not already created).
- Navigate to **Authentication** > Sign-in method and enable Google.
- Add the **Authorized domains** (make sure` localhost` is included for local testing).
- Replace the Firebase configuration details in the project’s `.env` file with your Firebase project's API keys. …
> Implemented Google authentication using Firebase

- src/components/Body.js
Feel free to share your suggestions and Hope it will merge as soon as possible
Happy coding! cheers🥂🥂
> Fix: Added responsiveness to Search component

- src/components/Footer.js
I have Updated the Footer Design, and now it is responsive and matching with the website's theme.
Please have a look at it and let me know if there's still any problem.  
Consider this PR under Hacktoberfest-accepted.
Issue: #46
BEFORE:
AFTER:
> UPDATE FOOTER DESIGN

- src/components/RestaurantCard.js
- Broadened the url area from just the food's name to the whole area where you can see the hover effect
- Removed the blue hover effect from food's name to fit the change I made
- Formatted the code to look cleaner and easier to read
https://github.com/user-attachments/assets/f5173447-55a6-42fa-b531-0b9e95938512
> Changing card hover effect for better UX and formatting the code

- index.css
- src/components/Header.js
Fixes #62 
1. Made Navbar Sticky.
2. Adjusted the height and width of the navbar.
3. Made the font more visually appealing.
> Update Nav Bar

- src/components/RestaurantMenu.js
- src/components/Shimmer.js
Sidebar should be fixed to avoid long scroll.
Fixed #58 
- Making the food details sidebar fixed.
https://github.com/user-attachments/assets/12040555-5a91-46d9-bb56-78144a0a0869
> Making sidebar fixed

- package-lock.json
- package.json
- src/components/Login.js
Implemented real-time password strength checker.
Bar increases with usage of uppercase & lowercase letters, numbers and special characters.
https://github.com/user-attachments/assets/faa47d1f-ef71-4528-bf74-1cc4eea948f0
@mohitahlawat2001 kindly review it.
> added password strength analyzer

- .dockerignore
- Dockerfile
- README.md
- docker-compose.yml
closes #77
Added .dokerignore, Dockerfile and docker-compose.yml file for Docker setup and updated Readme.
> Add Docker Support for Project Containerization and Setup

- vercel.json
I tried to run it locally, there was no issue. then i deployed it on vercel and the issued occured again. Then added vercel.json with neccesary code, it solved the issue in my deployment in vercel.
> Created vercel.json this will solve the issue #78

- src/components/Body.js
- src/components/Footer.js
> Fixed Search button

- LICENSE
added license file for broken link in readme file, now it is working fine.
> broken link: added license file
